/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_openhpsdr_dsp_Wdsp */

#ifndef _Included_org_openhpsdr_dsp_Wdsp
#define _Included_org_openhpsdr_dsp_Wdsp
#ifdef __cplusplus
extern "C" {
#endif
#undef org_openhpsdr_dsp_Wdsp_LSB
#define org_openhpsdr_dsp_Wdsp_LSB 0L
#undef org_openhpsdr_dsp_Wdsp_USB
#define org_openhpsdr_dsp_Wdsp_USB 1L
#undef org_openhpsdr_dsp_Wdsp_DSB
#define org_openhpsdr_dsp_Wdsp_DSB 2L
#undef org_openhpsdr_dsp_Wdsp_CWL
#define org_openhpsdr_dsp_Wdsp_CWL 3L
#undef org_openhpsdr_dsp_Wdsp_CWU
#define org_openhpsdr_dsp_Wdsp_CWU 4L
#undef org_openhpsdr_dsp_Wdsp_FM
#define org_openhpsdr_dsp_Wdsp_FM 5L
#undef org_openhpsdr_dsp_Wdsp_AM
#define org_openhpsdr_dsp_Wdsp_AM 6L
#undef org_openhpsdr_dsp_Wdsp_DIGU
#define org_openhpsdr_dsp_Wdsp_DIGU 7L
#undef org_openhpsdr_dsp_Wdsp_SPEC
#define org_openhpsdr_dsp_Wdsp_SPEC 8L
#undef org_openhpsdr_dsp_Wdsp_DIGL
#define org_openhpsdr_dsp_Wdsp_DIGL 9L
#undef org_openhpsdr_dsp_Wdsp_SAM
#define org_openhpsdr_dsp_Wdsp_SAM 10L
#undef org_openhpsdr_dsp_Wdsp_DRM
#define org_openhpsdr_dsp_Wdsp_DRM 11L
#undef org_openhpsdr_dsp_Wdsp_INACTIVE
#define org_openhpsdr_dsp_Wdsp_INACTIVE 0L
#undef org_openhpsdr_dsp_Wdsp_ACTIVE
#define org_openhpsdr_dsp_Wdsp_ACTIVE 1L
#undef org_openhpsdr_dsp_Wdsp_OFF
#define org_openhpsdr_dsp_Wdsp_OFF 0L
#undef org_openhpsdr_dsp_Wdsp_LONG
#define org_openhpsdr_dsp_Wdsp_LONG 1L
#undef org_openhpsdr_dsp_Wdsp_SLOW
#define org_openhpsdr_dsp_Wdsp_SLOW 2L
#undef org_openhpsdr_dsp_Wdsp_MED
#define org_openhpsdr_dsp_Wdsp_MED 3L
#undef org_openhpsdr_dsp_Wdsp_FAST
#define org_openhpsdr_dsp_Wdsp_FAST 4L
#undef org_openhpsdr_dsp_Wdsp_CUSTOM
#define org_openhpsdr_dsp_Wdsp_CUSTOM 5L
#undef org_openhpsdr_dsp_Wdsp_S_PK
#define org_openhpsdr_dsp_Wdsp_S_PK 0L
#undef org_openhpsdr_dsp_Wdsp_S_AV
#define org_openhpsdr_dsp_Wdsp_S_AV 1L
#undef org_openhpsdr_dsp_Wdsp_ADC_PK
#define org_openhpsdr_dsp_Wdsp_ADC_PK 2L
#undef org_openhpsdr_dsp_Wdsp_ADC_AV
#define org_openhpsdr_dsp_Wdsp_ADC_AV 3L
#undef org_openhpsdr_dsp_Wdsp_AGC_GAIN
#define org_openhpsdr_dsp_Wdsp_AGC_GAIN 4L
#undef org_openhpsdr_dsp_Wdsp_AGC_PK
#define org_openhpsdr_dsp_Wdsp_AGC_PK 5L
#undef org_openhpsdr_dsp_Wdsp_AGC_AV
#define org_openhpsdr_dsp_Wdsp_AGC_AV 6L
#undef org_openhpsdr_dsp_Wdsp_REAL
#define org_openhpsdr_dsp_Wdsp_REAL 0L
#undef org_openhpsdr_dsp_Wdsp_COMPLEX
#define org_openhpsdr_dsp_Wdsp_COMPLEX 1L
#undef org_openhpsdr_dsp_Wdsp_RECTANGULAR
#define org_openhpsdr_dsp_Wdsp_RECTANGULAR 0L
#undef org_openhpsdr_dsp_Wdsp_BLACKMAN_HARRIS
#define org_openhpsdr_dsp_Wdsp_BLACKMAN_HARRIS 1L
#undef org_openhpsdr_dsp_Wdsp_HANN
#define org_openhpsdr_dsp_Wdsp_HANN 2L
#undef org_openhpsdr_dsp_Wdsp_FLAT_TOP
#define org_openhpsdr_dsp_Wdsp_FLAT_TOP 3L
#undef org_openhpsdr_dsp_Wdsp_HAMMING
#define org_openhpsdr_dsp_Wdsp_HAMMING 4L
#undef org_openhpsdr_dsp_Wdsp_KAISER
#define org_openhpsdr_dsp_Wdsp_KAISER 5L
#undef org_openhpsdr_dsp_Wdsp_PEAK_DETECT
#define org_openhpsdr_dsp_Wdsp_PEAK_DETECT -1L
#undef org_openhpsdr_dsp_Wdsp_NO_AVERAGING
#define org_openhpsdr_dsp_Wdsp_NO_AVERAGING 0L
#undef org_openhpsdr_dsp_Wdsp_TIME_WEIGHTED_LINEAR
#define org_openhpsdr_dsp_Wdsp_TIME_WEIGHTED_LINEAR 1L
#undef org_openhpsdr_dsp_Wdsp_TIME_WEIGHTED_LOG
#define org_openhpsdr_dsp_Wdsp_TIME_WEIGHTED_LOG 2L
#undef org_openhpsdr_dsp_Wdsp_WINDOW_LINEAR
#define org_openhpsdr_dsp_Wdsp_WINDOW_LINEAR 3L
#undef org_openhpsdr_dsp_Wdsp_WINDOW_LOG
#define org_openhpsdr_dsp_Wdsp_WINDOW_LOG 4L
#undef org_openhpsdr_dsp_Wdsp_WEIGHTED_LINEAR_LOW_NOISE
#define org_openhpsdr_dsp_Wdsp_WEIGHTED_LINEAR_LOW_NOISE 5L
#undef org_openhpsdr_dsp_Wdsp_WEIGHTED_LOG_LOW_NOISE
#define org_openhpsdr_dsp_Wdsp_WEIGHTED_LOG_LOW_NOISE 6L
/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    GetWDSPVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_openhpsdr_dsp_Wdsp_GetWDSPVersion
  (JNIEnv *, jobject);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    WDSPwisdom
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_WDSPwisdom
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    OpenChannel
 * Signature: (IIIIIIIIDDDDI)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_OpenChannel
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint, jdouble, jdouble, jdouble, jdouble, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    CloseChannel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_CloseChannel
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetChannelState
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetChannelState
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    fexchange0
 * Signature: (I[D[D[I)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_fexchange0
  (JNIEnv *, jobject, jint, jdoubleArray, jdoubleArray, jintArray);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    fexchange2
 * Signature: (I[F[F[F[F[I)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_fexchange2
  (JNIEnv *, jobject, jint, jfloatArray, jfloatArray, jfloatArray, jfloatArray, jintArray);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAAGCMaxInputLevel
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAAGCMaxInputLevel
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAShiftRun
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAShiftRun
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAShiftFreq
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAShiftFreq
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAPreGenRun
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAPreGenRun
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAPreGenMode
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAPreGenMode
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAPreGenToneMag
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAPreGenToneMag
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAPreGenToneFreq
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAPreGenToneFreq
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAPreGenNoiseMag
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAPreGenNoiseMag
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAPreGenSweepMag
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAPreGenSweepMag
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAPreGenSweepFreq
 * Signature: (IDD)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAPreGenSweepFreq
  (JNIEnv *, jobject, jint, jdouble, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAPreGenSweepRate
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAPreGenSweepRate
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    GetRXAMeter
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_org_openhpsdr_dsp_Wdsp_GetRXAMeter
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    RXANBPSetRun
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_RXANBPSetRun
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    RXANBPSetWindow
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_RXANBPSetWindow
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    RXANBPSetNotchesRun
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_RXANBPSetNotchesRun
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    RXANBPGetMinNotchWidth
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_RXANBPGetMinNotchWidth
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    RXANBPSetAutoIncrease
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_RXANBPSetAutoIncrease
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    RXANBPSetTuneFrequency
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_RXANBPSetTuneFrequency
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    RXANBPSetShiftFrequency
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_RXANBPSetShiftFrequency
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    RXANBPGetNumNotches
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_RXANBPGetNumNotches
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    RXANBPAddNotch
 * Signature: (IIDDI)I
 */
JNIEXPORT jint JNICALL Java_org_openhpsdr_dsp_Wdsp_RXANBPAddNotch
  (JNIEnv *, jobject, jint, jint, jdouble, jdouble, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    RXANBPGetNotch
 * Signature: (IIDDI)I
 */
JNIEXPORT jint JNICALL Java_org_openhpsdr_dsp_Wdsp_RXANBPGetNotch
  (JNIEnv *, jobject, jint, jint, jdouble, jdouble, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    RXANBPDeleteNotch
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_openhpsdr_dsp_Wdsp_RXANBPDeleteNotch
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    RXANBPEditNotch
 * Signature: (IIDDI)I
 */
JNIEXPORT jint JNICALL Java_org_openhpsdr_dsp_Wdsp_RXANBPEditNotch
  (JNIEnv *, jobject, jint, jint, jdouble, jdouble, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXASpectrum
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXASpectrum
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAAMSQRun
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAAMSQRun
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    RXAAMSQThreshold
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_RXAAMSQThreshold
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAAMSQMaxTail
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAAMSQMaxTail
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAAMDSBMode
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAAMDSBMode
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAAMDFadeLevel
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAAMDFadeLevel
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAFMDeviation
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAFMDeviation
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXACTCSSRun
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXACTCSSRun
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXACTCSSFreq
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXACTCSSFreq
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAFMSQRun
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAFMSQRun
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAFMSQThreshold
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAFMSQThreshold
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXASNBARun
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXASNBARun
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAEQRun
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAEQRun
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAEQWinType
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAEQWinType
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAEQCtfmode
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAEQCtfmode
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAEQProfile
 * Signature: (IIDD)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAEQProfile
  (JNIEnv *, jobject, jint, jint, jdouble, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAAGCMode
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAAGCMode
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAAGCAttack
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAAGCAttack
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAAGCDecay
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAAGCDecay
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAAGCHang
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAAGCHang
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    GetRXAAGCHangLevel
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_GetRXAAGCHangLevel
  (JNIEnv *, jobject, jint, jdoubleArray);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAAGCHangLevel
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAAGCHangLevel
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    GetRXAAGCHangThreshold
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_GetRXAAGCHangThreshold
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAAGCHangThreshold
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAAGCHangThreshold
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    GetRXAAGCThresh
 * Signature: (IDDD)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_GetRXAAGCThresh
  (JNIEnv *, jobject, jint, jdoubleArray, jdouble, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAAGCThresh
 * Signature: (IDDD)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAAGCThresh
  (JNIEnv *, jobject, jint, jdouble, jdouble, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    GetRXAAGCTop
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_GetRXAAGCTop
  (JNIEnv *, jobject, jint, jdoubleArray);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAAGCTop
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAAGCTop
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAAGCSlope
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAAGCSlope
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAAGCFixed
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAAGCFixed
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAANFRun
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAANFRun
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAANFTaps
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAANFTaps
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAANFDelay
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAANFDelay
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAANFGain
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAANFGain
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAANFLeakage
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAANFLeakage
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAANFVals
 * Signature: (IIIDD)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAANFVals
  (JNIEnv *, jobject, jint, jint, jint, jdouble, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAANFPosition
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAANFPosition
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAANRRun
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAANRRun
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAANRTaps
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAANRTaps
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAANRDelay
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAANRDelay
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAANRGain
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAANRGain
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAANRLeakage
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAANRLeakage
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAANRVals
 * Signature: (IIIDD)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAANRVals
  (JNIEnv *, jobject, jint, jint, jint, jdouble, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAEMNRRun
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAEMNRRun
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAEMNRgainMethod
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAEMNRgainMethod
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAEMNRnpeMethod
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAEMNRnpeMethod
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAEMNRaeRun
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAEMNRaeRun
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAEMNRPosition
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAEMNRPosition
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXABandpassWindow
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXABandpassWindow
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    RXAGetaSipF
 * Signature: (IFI)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_RXAGetaSipF
  (JNIEnv *, jobject, jint, jfloatArray, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    RXAGetaSipF1
 * Signature: (IFI)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_RXAGetaSipF1
  (JNIEnv *, jobject, jint, jfloatArray, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXACBLRun
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXACBLRun
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXASPCWRun
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXASPCWRun
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXASPCWFreq
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXASPCWFreq
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXASPCWBandwidth
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXASPCWBandwidth
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXASPCWGain
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXASPCWGain
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAmpeakRun
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAmpeakRun
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAmpeakNpeaks
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAmpeakNpeaks
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAmpeakFilEnable
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAmpeakFilEnable
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAmpeakFilFreq
 * Signature: (IID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAmpeakFilFreq
  (JNIEnv *, jobject, jint, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAmpeakFilBw
 * Signature: (IID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAmpeakFilBw
  (JNIEnv *, jobject, jint, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAmpeakFilGain
 * Signature: (IID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAmpeakFilGain
  (JNIEnv *, jobject, jint, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAPanelRun
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAPanelRun
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAPanelSelect
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAPanelSelect
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAPanelGain1
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAPanelGain1
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAPanelGain2
 * Signature: (IDD)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAPanelGain2
  (JNIEnv *, jobject, jint, jdouble, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAPanelPan
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAPanelPan
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAPanelCopy
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAPanelCopy
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAPanelBinaural
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAPanelBinaural
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetRXAMode
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetRXAMode
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    RXASetPassband
 * Signature: (IDD)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_RXASetPassband
  (JNIEnv *, jobject, jint, jdouble, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    RXASetNC
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_RXASetNC
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    RXASetMP
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_RXASetMP
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAPreGenRun
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAPreGenRun
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAPreGenMode
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAPreGenMode
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAPreGenToneMag
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAPreGenToneMag
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAPreGenToneFreq
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAPreGenToneFreq
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAPreGenNoiseMag
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAPreGenNoiseMag
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAPreGenSweepMag
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAPreGenSweepMag
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAPreGenSweepFreq
 * Signature: (IDD)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAPreGenSweepFreq
  (JNIEnv *, jobject, jint, jdouble, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAPreGenSweepRate
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAPreGenSweepRate
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAPreGenSawtoothMag
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAPreGenSawtoothMag
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAPreGenSawtoothFreq
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAPreGenSawtoothFreq
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAPreGenTriangleMag
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAPreGenTriangleMag
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAPreGenTriangleFreq
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAPreGenTriangleFreq
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAPreGenPulseMag
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAPreGenPulseMag
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAPreGenPulseFreq
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAPreGenPulseFreq
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAPreGenPulseDutyCycle
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAPreGenPulseDutyCycle
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAPreGenPulseToneFreq
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAPreGenPulseToneFreq
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAPreGenPulseTransition
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAPreGenPulseTransition
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAPostGenRun
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAPostGenRun
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAPostGenMode
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAPostGenMode
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAPostGenToneMag
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAPostGenToneMag
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAPostGenToneFreq
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAPostGenToneFreq
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAPostGenTTMag
 * Signature: (IDD)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAPostGenTTMag
  (JNIEnv *, jobject, jint, jdouble, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAPostGenTTFreq
 * Signature: (IDD)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAPostGenTTFreq
  (JNIEnv *, jobject, jint, jdouble, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAPostGenSweepMag
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAPostGenSweepMag
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAPostGenSweepFreq
 * Signature: (IDD)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAPostGenSweepFreq
  (JNIEnv *, jobject, jint, jdouble, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAPostGenSweepRate
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAPostGenSweepRate
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAPanelRun
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAPanelRun
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAPanelSelect
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAPanelSelect
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAPanelGain1
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAPanelGain1
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAAMSQRun
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAAMSQRun
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAAMSQMutedGain
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAAMSQMutedGain
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAAMSQThreshold
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAAMSQThreshold
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAEQRun
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAEQRun
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAEQWintype
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAEQWintype
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAEQCtfmode
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAEQCtfmode
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAEQProfile
 * Signature: (IIDD)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAEQProfile
  (JNIEnv *, jobject, jint, jint, jdouble, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAFMEmphPosition
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAFMEmphPosition
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXALevelerSt
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXALevelerSt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXALevelerAttack
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXALevelerAttack
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXALevelerDecay
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXALevelerDecay
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXALevelerTop
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXALevelerTop
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAPHROTRun
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAPHROTRun
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAPHROTCorner
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAPHROTCorner
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAPHROTNstages
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAPHROTNstages
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXACFCOMPRun
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXACFCOMPRun
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXACFCOMPprofile
 * Signature: (IIDDD)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXACFCOMPprofile
  (JNIEnv *, jobject, jint, jint, jdouble, jdouble, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXACFCOMPPrecomp
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXACFCOMPPrecomp
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXACFCOMPPeqRun
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXACFCOMPPeqRun
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXACFCOMPPrePeq
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXACFCOMPPrePeq
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXABandpassFreqs
 * Signature: (IDD)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXABandpassFreqs
  (JNIEnv *, jobject, jint, jdouble, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXABandpassWindow
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXABandpassWindow
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXACompressorRun
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXACompressorRun
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXACompressorGain
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXACompressorGain
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAosctrlRun
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAosctrlRun
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAALCSt
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAALCSt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAALCAttack
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAALCAttack
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAALCDecay
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAALCDecay
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAALCMaxGain
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAALCMaxGain
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAAMCarrierLevel
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAAMCarrierLevel
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAFMDeviation
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAFMDeviation
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXACTCSSRun
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXACTCSSRun
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXACTCSSFreq
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXACTCSSFreq
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    TXASetSipMode
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_TXASetSipMode
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    TXASetSipDisplay
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_TXASetSipDisplay
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    TXAGetaSipF
 * Signature: (IFI)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_TXAGetaSipF
  (JNIEnv *, jobject, jint, jfloatArray, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    TXAGetaSipF1
 * Signature: (IFI)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_TXAGetaSipF1
  (JNIEnv *, jobject, jint, jfloatArray, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    TXAGetaSpecF1
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_TXAGetaSpecF1
  (JNIEnv *, jobject, jint, jfloatArray);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    TXASetSipSpecmode
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_TXASetSipSpecmode
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXACFIRRun
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXACFIRRun
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetTXAMode
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetTXAMode
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    TXASetNC
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_TXASetNC
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    TXASetMP
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_TXASetMP
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    XCreateAnalyzer
 * Signature: (I[IIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_XCreateAnalyzer
  (JNIEnv *, jobject, jint, jintArray, jint, jint, jint, jstring);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    DestroyAnalyzer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_DestroyAnalyzer
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetAnalyzer
 * Signature: (IIII[IIIIDIIIIIIIDDI)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetAnalyzer
  (JNIEnv *, jobject, jint, jint, jint, jint, jintArray, jint, jint, jint, jdouble, jint, jint, jint, jint, jint, jint, jint, jdouble, jdouble, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetCalibration
 * Signature: (III[D)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetCalibration
  (JNIEnv *, jobject, jint, jint, jint, jdoubleArray);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetDisplayDetectorMode
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetDisplayDetectorMode
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetDisplayAverageMode
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetDisplayAverageMode
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetDisplayNumAverage
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetDisplayNumAverage
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetDisplayAvBackmult
 * Signature: (IID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetDisplayAvBackmult
  (JNIEnv *, jobject, jint, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetDisplaySampleRate
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetDisplaySampleRate
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetDisplayNormOneHz
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetDisplayNormOneHz
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    Spectrum2
 * Signature: (IIIID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_Spectrum2
  (JNIEnv *, jobject, jint, jint, jint, jint, jdoubleArray);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    Spectrum0
 * Signature: (IIIID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_Spectrum0
  (JNIEnv *, jobject, jint, jint, jint, jint, jdoubleArray);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    Spectrum
 * Signature: (IIIDD)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_Spectrum
  (JNIEnv *, jobject, jint, jint, jint, jdoubleArray, jdoubleArray);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    GetPixels
 * Signature: (II[F[I)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_GetPixels
  (JNIEnv *, jobject, jint, jint, jfloatArray, jintArray);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    create_anb
 * Signature: (IIDDDDDDDD)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_create_anb
  (JNIEnv *, jobject, jint, jint, jdoubleArray, jdoubleArray, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    create_nob
 * Signature: (IIDDDIDDDDDDD)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_create_nob
  (JNIEnv *, jobject, jint, jint, jdoubleArray, jdoubleArray, jdouble, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    create_nobEXT
 * Signature: (IIIIDDDDDD)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_create_nobEXT
  (JNIEnv *, jobject, jint, jint, jint, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    destroy_nobEXT
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_destroy_nobEXT
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    flush_nobEXT
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_flush_nobEXT
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    xnobEXT
 * Signature: (IDD)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_xnobEXT
  (JNIEnv *, jobject, jint, jdoubleArray, jdoubleArray);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetEXTNOBRun
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetEXTNOBRun
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetEXTNOBMode
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetEXTNOBMode
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetEXTNOBSamplerate
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetEXTNOBSamplerate
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetEXTNOBBuffsize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetEXTNOBBuffsize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetEXTNOBTau
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetEXTNOBTau
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetEXTNOBHangtime
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetEXTNOBHangtime
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetEXTNOBAdvtime
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetEXTNOBAdvtime
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetEXTNOBBacktau
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetEXTNOBBacktau
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     org_openhpsdr_dsp_Wdsp
 * Method:    SetEXTANBNOBThreshold
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_org_openhpsdr_dsp_Wdsp_SetEXTANBNOBThreshold
  (JNIEnv *, jobject, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
